### ISSUE TITLE
[BUG] Syntax error in query?

### ISSUE THREAD

**Issue by kurogeek** [frappe/helpdesk#1150] opened 2023-05-05 09:35 UTC
When I go to the endpoint `/helpdesk/contacts/contact_name`, I got an error below.

![image](https://user-images.githubusercontent.com/7752934/236422553-48e2bc63-703e-483f-8f71-8c0a6bdd7256.png)

Then I tied to use that query statement on my mysql-client using the statement below. And I got the error below.

**Problematic statement**
```SELECT `_assign`,`status`,`priority`,`subject`,`ticket_type`,`creation`,`modified`,`name`,`_seen`,* FROM `tabHD Ticket` WHERE `contact`=%(param1)s ORDER BY `modified` DESC,`modified` DESC LIMIT 3 {'param1': 'Frappe Helpdesk Team'} ;```

**The error**
```ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '* FROM `tabHD Ticket` WHERE `contact`=%(param1)s ORDER BY `modified` DESC,`mo...' at line 1```

Then I tried to rewrite the statement to:
```SELECT `_assign`,`status`,`priority`,`subject`,`ticket_type`,`creation`,`modified`,`name`,`_seen` FROM `tabHD Ticket` WHERE `contact`='Frappe Helpdesk Team' ORDER BY `modified` DESC,`modified` DESC LIMIT 3 ;```
And this seem to be working.

So, is this query statement a legitimate sql statement? or am I missing something such as Maria DB version?

If this is a bug, I can help you fix it.

**Comment by ssiyad** [comment] 2023-05-05 10:01
I am not able to reproduce this exact issue. But I found something else and might be related - https://github.com/frappe/helpdesk/pull/1151

**Comment by ssiyad** [comment] 2023-05-05 10:02
For context, my MariaDB version is `10.9.4`

**Comment by ssiyad** [comment] 2023-05-05 10:03
What version is your Frappe Framework?

**Comment by kurogeek** [comment] 2023-05-05 10:05
I was testing on `frappe 14.35.0`

**Comment by ssiyad** [comment] 2023-05-05 13:44
Fixed in https://github.com/frappe/helpdesk/issues/1150

**Closed** 2023-05-05 13:44 UTC
